MOSIP-36219 - The PMS (and eSignet) Create OIDC endpoints allow duplicate public key
mosip/partner-management-services pull request #928
Opened 2024-10-10 12:50 UTC by Sudeep7353

2024-10-15 06:20 UTC, mayuradesh requested changes
Awaiting design discussion with Esignet team

2024-10-15 10:43 UTC, mayuradesh requested changes
Comments from Taheer:
1. Check the algo to be RSA
2. Support for other algo ECC and ED25519
3. E Signet can have similar checks at their side

2024-10-16 11:18 UTC, mahammedtaheer approved these changes

2024-10-16 13:08 UTC, mayuradesh approved these changes

2024-10-16 13:18 UTC, merged