[MOSIP-36423] - Automated GetAllDeviceListMappedWithSbi
mosip/partner-management-services pull request #939
Opened 2024-10-18 13:09 UTC by prathmeshj12

2024-10-23 11:40 UTC, mohanachandran-s approved these changes

2024-10-23 11:45 UTC, mohanachandran-s requested changes

2024-10-23 11:45 UTC, mohanachandran-s commented on api-test/src/main/resources/pms/DeactivateDevice/DeactivateDeviceNegativeScenarios.yml
> +DeactivateDevice:
Update this as per the xml file

2024-10-23 11:51 UTC, mohanachandran-s requested changes

2024-10-23 11:51 UTC, mohanachandran-s commented on api-test/src/main/resources/pms/DeactivateDevice/DeactivateDeviceNegativeScenarios.yml
Add "Neg", at the end of all negative testcases and also update the expectation in each test description

2024-10-23 11:51 UTC, mohanachandran-s commented on api-test/src/main/resources/pms/DeactivateSBIWithAssociatedDevices/DeactivateSBIWithAssociatedDevicesNegativeScenarios.yml
> +	  "version": "1.0",
correct the indentation

2024-10-23 11:51 UTC, mohanachandran-s commented on api-test/src/main/resources/pms/DeactivateSBIWithAssociatedDevices/DeactivateSBIWithAssociatedDevicesNegativeScenarios.yml
> +	  "version": "1.0",
correct the indentation

2024-10-24 09:29 UTC, prathmeshj12 commented on api-test/src/main/resources/pms/DeactivateSBIWithAssociatedDevices/DeactivateSBIWithAssociatedDevicesNegativeScenarios.yml
corrected the indentation

2024-10-24 09:30 UTC, prathmeshj12 commented on api-test/src/main/resources/pms/DeactivateSBIWithAssociatedDevices/DeactivateSBIWithAssociatedDevicesNegativeScenarios.yml
> +	  "version": "1.0",
corrected the indentation

2024-10-24 09:30 UTC, prathmeshj12 commented on api-test/src/main/resources/pms/DeactivateSBIWithAssociatedDevices/DeactivateSBIWithAssociatedDevicesNegativeScenarios.yml
> +	  "version": "1.0",
corrected the indentation

2024-10-24 09:30 UTC, prathmeshj12 commented on api-test/src/main/resources/pms/DeactivateDevice/DeactivateDeviceNegativeScenarios.yml
corrected the indentation and added Neg

2024-10-24 09:30 UTC, prathmeshj12 commented on api-test/src/main/resources/pms/DeactivateDevice/DeactivateDeviceNegativeScenarios.yml
> +DeactivateDevice:
Updated as per xml file

2024-10-24 10:12 UTC, mohanachandran-s approved these changes

2024-10-25 04:03 UTC, mohanachandran-s approved these changes

2024-10-25 04:52 UTC, mayuradesh approved these changes

2024-10-25 05:09 UTC, merged